### ISSUE TITLE
Can't find inline() on released lib

### ISSUE THREAD

**Issue by bernardoatworkpop** [threepointone/glamor-stream#2]
Hello,

I'm trying to  get a server-side stream render working using the local examples, but apparently /lib/index.js (which should include the inline method) is not being published on the releases.
This causes a server side error when attempting to invoke inline(), when imported from 'glamor-stream'.

Is there a different way to access it?

Thanks,

 - B

**Comment by subpopular** [comment]
Looks like it didn't get in the published release. You could just `cd ./node_modules/glamor-stream && yarn && yarn build` locally in the meantime.

**Comment by threepointone** [comment]
whoops, sorry about that, fixed in 1.0.4
